name: Deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #run: |
        #echo "Cloning repository"
        #echo "${{toJson(github)}}"
        #git clone https://github.com/${{github.repository}}.git my-project
        #cd my-project
        #ls -lt
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache
        id: cache
        uses: actions/cached@v4
        with:
          path: node_modules
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build project
        run: npm run build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployment completed'
