name: Deploy
on: 
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - README.md
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #run: |
        #echo "Cloning repository"
        #echo "${{toJson(github)}}"
        #git clone https://github.com/${{github.repository}}.git my-project
        #cd my-project
        #ls -lt
      - name: Step up node and install dependencies
        uses: ./.github/actions/setupnode
      - name: Run tests
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step up node and install dependencies
        uses: ./.github/actions/setupnode
      - name: Build project
        run: npm run build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployment completed'
