name: Greet User
on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greet user in en
        run: echo "Hello $USER"
      - name: greet user in fr
        run: echo "Bonjour $USER"